# Tensor 기초

In [1]:
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn  # 딥러닝, 즉 인공 신경망 모델을 설계할 때 필요한 함수를 모아 놓은 모듈
import torch.nn.functional as F  # 그 중 자주 사용되는 함수

## Scalar

In [2]:
scalar1 = torch.tensor([1.]) # Scalar 생성
scalar2 = torch.tensor([3.]) # Scalar 생성

print(scalar1, scalar2)

tensor([1.]) tensor([3.])


In [3]:
add_scalar = scalar1 + scalar2
print(add_scalar)

tensor([4.])


In [4]:
sub_scalar = scalar1 - scalar2
print(sub_scalar)

tensor([-2.])


In [5]:
mul_scalar = scalar1 * scalar2
print(mul_scalar)

tensor([3.])


In [6]:
div_scalar = scalar1 / scalar2
print(div_scalar)

tensor([0.3333])


In [7]:
torch.add(scalar1, scalar2)

tensor([4.])

In [8]:
torch.sub(scalar1, scalar2)

tensor([-2.])

In [9]:
torch.mul(scalar1, scalar2)

tensor([3.])

In [10]:
torch.div(scalar1, scalar2)

tensor([0.3333])

## Vector

In [11]:
vector1 = torch.tensor([1., 2., 3.]) # 1D tensor 생성
vector2 = torch.tensor([4., 5., 6.]) # 1D tensor 생성

print(vector1)
print(vector2)

tensor([1., 2., 3.])
tensor([4., 5., 6.])


In [12]:
add_vector = vector1 + vector2
torch_add_vector = torch.add(vector1, vector2)

assert torch.equal(add_vector, torch_add_vector) # 두 텐서가 같은지 확인
print(add_vector)

tensor([5., 7., 9.])


In [13]:
sub_vector = vector1 - vector2
torch_sub_vector = torch.sub(vector1, vector2)

assert torch.equal(sub_vector, torch_sub_vector)
print(sub_vector)

tensor([-3., -3., -3.])


In [14]:
mul_vector = vector1 * vector2
torch_mul_vector = torch.mul(vector1, vector2)

assert torch.equal(mul_vector, torch_mul_vector)
print(mul_vector)

tensor([ 4., 10., 18.])


In [15]:
div_vector = vector1 / vector2
torch_div_vector = torch.div(vector1, vector2)

assert torch.equal(div_vector, torch_div_vector)
print(div_vector)

tensor([0.2500, 0.4000, 0.5000])


In [16]:
torch.dot(vector1, vector2) # 두 벡터의 내적 반환

tensor(32.)

## Matrix

In [17]:
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
matrix2 = torch.tensor([[5., 6.], [7., 8.]])

print(matrix1)
print(matrix2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [18]:
assert torch.equal(matrix1 + matrix2, torch.add(matrix1, matrix2))
assert torch.equal(matrix1 - matrix2, torch.sub(matrix1, matrix2))
assert torch.equal(matrix1 * matrix2, torch.mul(matrix1, matrix2))
assert torch.equal(matrix1 / matrix2, torch.div(matrix1, matrix2))

## Tensor

In [19]:
tensor1 = torch.tensor([[[1., 2.], [3., 4.]], [[5., 6.], [7., 8.]]])
tensor2 = torch.tensor([[[9., 10.], [11., 12.]], [[13., 14.], [15., 16.]]])

print(tensor1)
print(tensor2)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[ 9., 10.],
         [11., 12.]],

        [[13., 14.],
         [15., 16.]]])


In [20]:
assert torch.equal(tensor1 + tensor2, torch.add(tensor1, tensor2))
assert torch.equal(tensor1 - tensor2, torch.sub(tensor1, tensor2))
assert torch.equal(tensor1 * tensor2, torch.mul(tensor1, tensor2))
assert torch.equal(tensor1 / tensor2, torch.div(tensor1, tensor2))

In [21]:
torch.matmul(tensor1, tensor2) # 행렬 곱 수행

tensor([[[ 31.,  34.],
         [ 71.,  78.]],

        [[155., 166.],
         [211., 226.]]])

# Tensor 조작

## 1차원 배열

In [22]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [23]:
print(t.dim()) # 텐서 t의 차원을 출력
print(t.shape) # 텐서 t의 형태(shape)를 출력
print(t.size()) # 텐서 t의 크기를 출력

print(t[0], t[1], t[-1]) # 인덱싱을 통해 특정 요소에 접근 (파이썬 리스트와 유사하게 작동)

print(t[2:5], t[4:-1]) # 텐서 t의 특정 부분을 슬라이싱하여 출력
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2차원 배열

In [24]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [25]:
print(t.dim()) # 텐서 t의 차원을 출력
print(t.size()) # 텐서 t의 크기를 출력

print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Shape, Rank, Axis
- Shape는 텐서의 형태를 나타내며, 각 차원의 크기를 포함한 튜플
- Rank는 텐서의 차원의 수로 텐서가 몇 개의 축(axis)을 가지고 있는지를 나타내는 값
- Axis는 텐서의 특정 차원으로 각 차원은 하나의 축으로 표현

In [26]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                       ]])

In [27]:
print(t.dim())  # rank  = 4
print(t.size()) # shape = (1, 2, 3, 4) # 1개의 샘플, 2개의 채널, 3개의 행, 4개의 열

4
torch.Size([1, 2, 3, 4])


## Mul vs. Matmul
- 	Mul은 요소별 곱셈(element-wise multiplication)을 수행하는 연산
    - 피연산자들의 크기가 같거나 브로드캐스팅 조건을 만족할 때 사용
    - 각 위치에 있는 요소들끼리 곱셈을 수행
- Matmul은 행렬 곱셈(matrix multiplication)을 수행하는 연산
    - 행렬의 곱셈 규칙을 따르며 첫 번째 행렬의 열 수와 두 번째 행렬의 행 수가 일치해야 함
    - 행렬의 내적을 계산하여 새로운 행렬을 생성

In [28]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [29]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # element-wise multiplication

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Broadcasting
- 브로드캐스팅(Broadcasting)은 다양한 크기의 배열 간에 연산을 허용하는 메커니즘
- 크기가 다른 텐서(tensor)들 사이의 연산을 수행할 때 자동으로 크기를 조정하여 연산을 가능하게 함

In [30]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [31]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # 1 x 2
m2 = torch.FloatTensor([[3], [4]]) # 2 x 1
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Aggregation
- 텐서의 여러 요소에 걸쳐 연산을 수행하여 하나의 요약된 값(또는 더 작은 집합의 값)을 얻는 과정
- 이러한 연산은 데이터의 차원을 축소하거나, 텐서의 중요한 통계적 정보를 추출할 때 사용
- 집계 함수는 일반적으로 전체 텐서에 대해 적용할 수 있으며, 특정 차원(axis)을 기준으로 연산을 수행하도록 지정할 수도 있음
- Sum, Mean, Min, Max, Standard Deviation, Variance, Median, Mode 등

In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [33]:
# 평균
print(t.mean())
print(t.mean(dim=0)) # 행 기준 (모든 행을 통틀어 열을) 연산
print(t.mean(dim=1)) # 열 기준 (모든 열을 통틀어 행을) 연산
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [34]:
# Max: 최댓값
# Argmax: 최댓값의 인덱스
print(t.max()) # max 한 개의 값
print(t.max(dim=0)) # max와 argmax 두 개의 값 반환

print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [35]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View
- 기존의 텐서의 데이터를 변경하지 않고, 텐서의 형태(shape)를 재배열하는 연산
- view 연산을 사용하면 텐서의 차원을 변환하거나 재배열할 수 있음

In [36]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [37]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [38]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze
- 텐서에서 크기가 1인 차원(dimension)을 제거하는 역할
- 즉, 차원 크기가 1인 축을 삭제하여 텐서의 차원을 줄이는 데 사용


In [39]:
ft = torch.FloatTensor([[0], [1], [2]])

print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze
- 텐서에 새로운 차원을 추가하는 역할
- 기존 텐서에 크기가 1인 차원을 삽입하여 텐서의 차원을 늘리는 데 사용

In [41]:
ft = torch.Tensor([0, 1, 2])

print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [42]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [43]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [44]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Scatter
- 주어진 인덱스를 사용해 소스 텐서의 값을 목표 텐서의 특정 위치에 분산시키는 연산
- 목표 텐서의 특정 차원에 값을 할당하거나 업데이트할 때 유용하며, 인덱스가 가리키는 위치에 소스 텐서의 값을 복사
- 주로, one-hot encoding을 위해 사용


In [45]:
lt = torch.LongTensor([[0], [1], [2], [0]])

print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [46]:
one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)

print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


## Casting
- 텐서의 데이터 타입을 변경하는 연산
- 이 연산은 데이터의 형태를 유지하면서도 연산에 필요한 적절한 데이터 타입으로 변환

In [47]:
lt = torch.LongTensor([1, 2, 3, 4])

print(lt)

tensor([1, 2, 3, 4])


In [48]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [49]:
bt = torch.ByteTensor([True, False, False, True])

print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [50]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenation
- 여러 개의 텐서를 특정 차원(axis)을 따라 연결하여 하나의 텐서로 합치는 연산
- 예를 들어, 두 개의 2D 텐서를 행(row) 또는 열(column) 방향으로 이어 붙이는 데 사용

In [51]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [52]:
print(torch.cat([x, y], dim=0)) # 행 기준 (모든 행을 통틀어 열을) 연산
print(torch.cat([x, y], dim=1)) # 열 기준 (모든 열을 통틀어 행을) 연산

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking
- 여러 텐서를 새로운 차원(axis)을 추가하면서 쌓아 하나의 텐서로 만드는 연산
- 예를 들어, 여러 2D 텐서를 쌓아 3D 텐서를 만드는 방식

In [53]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [54]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [55]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros Like
- ones_like 연산은 입력 텐서와 동일한 형태(shape)를 가지면서 모든 값을 1로 채운 새로운 텐서를 생성하는 연산
- zeros_like 연산은 동일한 형태의 텐서를 생성하되, 모든 값을 0으로 채우는 연산
- 두 연산 모두 입력 텐서의 형태를 유지하면서 초기화된 텐서를 만드는 데 사용

In [56]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [57]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation
- 텐서의 값을 직접 수정하여 변경된 결과를 새로운 메모리 공간에 저장하지 않고, 기존의 메모리 공간에 바로 반영하는 연산
- PyTorch에서는 이러한 연산이 보통 연산자 뒤에 _ 가 붙어 표시되며, 예를 들어 add_()나 scatter_()가 이에 해당

In [58]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [59]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


# Autograd
- PyTorch에서 자동 미분을 수행하는 기능으로, 텐서의 연산 기록을 추적하고, 역전파(backpropagation) 시 각 연산에 대한 미분(gradient)을 자동으로 계산
- 이를 통해 신경망의 학습 과정에서 파라미터의 기울기를 손쉽게 구할 수 있음

In [61]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
else:
    DEVICE = torch.device('cpu')

print('Using PyTorch version:', torch.__version__, ' Device:', DEVICE)

Using PyTorch version: 2.4.0+cu121  Device: cpu


----